-- This is a script for Project #1 - Reimbursement System
-- Creator: Jian Qiu
-- Date: 04/12/2020

CREATE TABLE EMPLOYEE (
EMPLOYEE_ID INT PRIMARY KEY AUTO_INCREMENT,
EMPLOYEE_NAME VARCHAR(200),
USER_NAME VARCHAR(200),
USER_PASSWORD VARCHAR(200)
);

SELECT * FROM EMPLOYEE;

INSERT INTO EMPLOYEE VALUES(0, 'Jian Qiu', 'jian', 'j123');
INSERT INTO EMPLOYEE VALUES(0, 'Peter Lee', 'peter', 'p1p2');
INSERT INTO EMPLOYEE VALUES(0, 'Svitak Omia', 'svitak', 'vita');



CREATE TABLE MANAGER (
MANAGER_ID INT PRIMARY KEY AUTO_INCREMENT,
MANAGER_NAME VARCHAR(200),
USER_NAME VARCHAR(200),
USER_PASSWORD VARCHAR(200)
);


SELECT * FROM MANAGER;

INSERT INTO MANAGER VALUES(0, 'Jian Qiu', 'jianq', '3314');
INSERT INTO MANAGER VALUES(0, 'Maria Lola', 'lola', 'ppaa1');
INSERT INTO MANAGER VALUES(0, 'Pecho Kivi', 'kivi', 'lala2');


CREATE TABLE REIMBURSEMENT(
REIMBURSEMENT_ID INT PRIMARY KEY AUTO_INCREMENT,
AMOUNT INT,
DESCRIPTION VARCHAR(200),
REIMBURSEMENT_DATETIME VARCHAR(200),
REQUESTER_ID INT,
STATUS VARCHAR(200),
CONSTRAINT FK_REIMBURSEMENT_EMPLOYEE FOREIGN KEY REIMBURSEMENT(REQUESTER_ID) REFERENCES EMPLOYEE(EMPLOYEE_ID)
);


SELECT * FROM REIMBURSEMENT;

INSERT INTO REIMBURSEMENT VALUES(0, 150, 'commuting cost', '2020.4.12.21.05.00', 1, 'Pending');
INSERT INTO REIMBURSEMENT VALUES(0, 400, 'laptop', '2020.4.15.09.05.00', 1, 'Approved');
INSERT INTO REIMBURSEMENT VALUES(0, 1000, 'housing', '2020.4.12.21.05.00', 1, 'Denied');
INSERT INTO REIMBURSEMENT VALUES(0, 150, 'commuting cost', '2020.4.05.13.05.00', 2, 'Pending');
INSERT INTO REIMBURSEMENT VALUES(0, 150, 'commuting cost', '2020.3.11.11.05.00', 3, 'Pending');

